name       : gnome-todo
version    : 3.28.1
release    : 14
homepage   : https://wiki.gnome.org/Apps/Todo
source     :
    - https://download.gnome.org/sources/gnome-todo/3.28/gnome-todo-3.28.1.tar.xz : c7571fc040d8901dd0e528282ef0655687f23f29d304057c72548ab3e2c2cf23
license    : GPL-3.0-only
component  : office.notes
summary    : Minimalistic personal task manager designed to fit GNOME desktop
description: |
    GNOME To Do is a simplistic personal task manager designed to perfectly fit the GNOME desktop. Designed from ground up to seamlessly integrate with the GNOME desktop environment, To Do enables you to be as productive as you want.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(rest-0.7)
    - gnome-common
    - gtk-doc
setup      : |
    %meson_configure -Denable-gtk-doc=true
build      : |
    %meson_build
install    : |
    %meson_install
