name       : gnome-todo
version    : 3.22.1
release    : 6
homepage   : https://wiki.gnome.org/Apps/Todo
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-todo/3.22/gnome-todo-3.22.1.tar.xz : cb80f64f5edeeac7b221146d2203bd1bebc49d275b7a41e7a5418f409d9c74af
license    : GPL-3.0
component  : office.notes
summary    : Minimalistic personal task manager designed to fit GNOME desktop
description: |
    GNOME To Do is a simplistic personal task manager designed to perfectly fit the GNOME desktop. Designed from ground up to seamlessly integrate with the GNOME desktop environment, To Do enables you to be as productive as you want.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libpeas-1.0)
    - gnome-common
setup      : |
    %configure --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
