name        : gnome-todo
version     : 3.18.1
release     : 2
homepage    : https://wiki.gnome.org/Apps/Todo
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-todo/3.18/gnome-todo-3.18.1.tar.xz : 7da17c39f46accb897b8af159f6accabc4e2afa4503d8d36138b5937cf5bcc51
license     : GPL-3.0
summary     : Minimalistic personal task manager designed to fit GNOME desktop
builddeps   :
    - pkgconfig(appstream-glib)
    - gnome-common
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(libical)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(goa-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
description : |
    GNOME To Do is a simplistic personal task manager designed to perfectly fit the GNOME desktop. Designed from ground up to seamlessly integrate with the GNOME desktop environment, To Do enables you to be as productive as you want.
setup       : |
    %configure --disable-schemas-compile
build       : |
    %make
install     : |
    %make_install
