name       : gnome-todo
version    : 3.24.0.1
release    : 8
homepage   : https://wiki.gnome.org/Apps/Todo
source     :
    - https://download.gnome.org/sources/gnome-todo/3.24/gnome-todo-3.24.0.1.tar.xz : 65311020613322c03b05dc6e7fac32c7d5ee3529f1a76ba2533a2fb998ed35cb
license    : GPL-3.0
component  : office.notes
summary    : Minimalistic personal task manager designed to fit GNOME desktop
description: |
    GNOME To Do is a simplistic personal task manager designed to perfectly fit the GNOME desktop. Designed from ground up to seamlessly integrate with the GNOME desktop environment, To Do enables you to be as productive as you want.
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(evolution-data-server-1.2)
    - pkgconfig(goa-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libical)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libpeas-1.0)
    - gnome-common
setup      : |
    %configure --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
